spring:                   #生产环境  日志级别高
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none   #生产环境  表不能随意更改
    show-sql: true    #把sql语句输出到控制台

logging:
  level:
    root: warn
    com.lt: info
  file: log/blog-pro.log
server:
  port: 8081
